minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - errx
  - clickable-path
  - '@nuxt/kit-nightly@5.0.0-29806258.d070492f'
  - '@nuxt/nitro-server-nightly@5.0.0-29806258.d070492f'
  - '@nuxt/schema-nightly@5.0.0-29806258.d070492f'
  - '@nuxt/vite-builder-nightly@5.0.0-29806258.d070492f'
  - '@nuxt/vite-server-nightly@5.0.0-29806258.d070492f'
  - nuxt-nightly@5.0.0-29806258.d070492f

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

shellEmulator: true

packages:
  - playground
  - playground/vite
  - test/fixtures/*

overrides:
  my-bad: 'link:.'

allowBuilds:
  esbuild: false
  simple-git-hooks: true
